#!/usr/bin/env bash
test_dir="tests"
root_dir=$PWD

rm -fv CTestTestfile.cmake CMakeCache.txt cmake_install.cmake Makefile gltest czanalyse.txt gmon.out vgcore.* slicetest
rm -rf CMakeFiles/ Testing/ build/*


cd $root_dir/$test_dir
./clean

